//! オペコードを命令ユニット `Instr` に変換する純粋関数(実行はしない)。

use super::exec::*;
use super::instr::{ExecFn, Instr};
use super::operand::{Cond, Indirect, Operand, Reg8, Reg16};

// オペランド構築ショートハンド
const N: Operand = Operand::None;
const IMM: Operand = Operand::Imm;
fn r(r: Reg8) -> Operand {
    Operand::Reg8(r)
}
fn rr(r: Reg16) -> Operand {
    Operand::Reg16(r)
}
fn ind(i: Indirect) -> Operand {
    Operand::Ind(i)
}
fn cc(c: Cond) -> Operand {
    Operand::Cond(c)
}

fn ld(dst: Operand, src: Operand) -> Instr {
    Instr::with(dst, src, exec_ld8)
}
fn alu(exec: ExecFn, src: Operand) -> Instr {
    Instr::with(N, src, exec)
}

/// オペコード → 命令ユニット
pub(super) fn decode(opcode: u8) -> Instr {
    use Reg8::*;
    use Reg16::*;
    match opcode {
        0x00 => Instr::simple(exec_nop),
        0x01 => Instr::with(rr(BC), N, exec_ld16),
        0x02 => ld(ind(Indirect::BC), r(A)),
        0x03 => Instr::with(rr(BC), N, exec_inc16),
        0x04 => Instr::with(r(B), N, exec_inc8),
        0x05 => Instr::with(r(B), N, exec_dec8),
        0x06 => ld(r(B), IMM),
        0x07 => Instr::simple(exec_rlca),
        0x08 => Instr::simple(exec_ld_nn_sp),
        0x09 => alu(exec_add_hl, rr(BC)),
        0x0A => ld(r(A), ind(Indirect::BC)),
        0x0B => Instr::with(rr(BC), N, exec_dec16),
        0x0C => Instr::with(r(C), N, exec_inc8),
        0x0D => Instr::with(r(C), N, exec_dec8),
        0x0E => ld(r(C), IMM),
        0x0F => Instr::simple(exec_rrca),
        0x10 => Instr::simple(exec_stop),
        0x11 => Instr::with(rr(DE), N, exec_ld16),
        0x12 => ld(ind(Indirect::DE), r(A)),
        0x13 => Instr::with(rr(DE), N, exec_inc16),
        0x14 => Instr::with(r(D), N, exec_inc8),
        0x15 => Instr::with(r(D), N, exec_dec8),
        0x16 => ld(r(D), IMM),
        0x17 => Instr::simple(exec_rla),
        0x18 => Instr::with(N, N, exec_jr),
        0x19 => alu(exec_add_hl, rr(DE)),
        0x1A => ld(r(A), ind(Indirect::DE)),
        0x1B => Instr::with(rr(DE), N, exec_dec16),
        0x1C => Instr::with(r(E), N, exec_inc8),
        0x1D => Instr::with(r(E), N, exec_dec8),
        0x1E => ld(r(E), IMM),
        0x1F => Instr::simple(exec_rra),
        0x20 => Instr::with(N, cc(Cond::NZ), exec_jr),
        0x21 => Instr::with(rr(HL), N, exec_ld16),
        0x22 => ld(ind(Indirect::HLI), r(A)),
        0x23 => Instr::with(rr(HL), N, exec_inc16),
        0x24 => Instr::with(r(H), N, exec_inc8),
        0x25 => Instr::with(r(H), N, exec_dec8),
        0x26 => ld(r(H), IMM),
        0x27 => Instr::simple(exec_daa),
        0x28 => Instr::with(N, cc(Cond::Z), exec_jr),
        0x29 => alu(exec_add_hl, rr(HL)),
        0x2A => ld(r(A), ind(Indirect::HLI)),
        0x2B => Instr::with(rr(HL), N, exec_dec16),
        0x2C => Instr::with(r(L), N, exec_inc8),
        0x2D => Instr::with(r(L), N, exec_dec8),
        0x2E => ld(r(L), IMM),
        0x2F => Instr::simple(exec_cpl),
        0x30 => Instr::with(N, cc(Cond::NC), exec_jr),
        0x31 => Instr::with(rr(SP), N, exec_ld16),
        0x32 => ld(ind(Indirect::HLD), r(A)),
        0x33 => Instr::with(rr(SP), N, exec_inc16),
        0x34 => Instr::with(ind(Indirect::HL), N, exec_inc8),
        0x35 => Instr::with(ind(Indirect::HL), N, exec_dec8),
        0x36 => ld(ind(Indirect::HL), IMM),
        0x37 => Instr::simple(exec_scf),
        0x38 => Instr::with(N, cc(Cond::C), exec_jr),
        0x39 => alu(exec_add_hl, rr(SP)),
        0x3A => ld(r(A), ind(Indirect::HLD)),
        0x3B => Instr::with(rr(SP), N, exec_dec16),
        0x3C => Instr::with(r(A), N, exec_inc8),
        0x3D => Instr::with(r(A), N, exec_dec8),
        0x3E => ld(r(A), IMM),
        0x3F => Instr::simple(exec_ccf),

        // LD r,r' (0x40-0x7F, 0x76 は HALT)
        0x40 => ld(r(B), r(B)),
        0x41 => ld(r(B), r(C)),
        0x42 => ld(r(B), r(D)),
        0x43 => ld(r(B), r(E)),
        0x44 => ld(r(B), r(H)),
        0x45 => ld(r(B), r(L)),
        0x46 => ld(r(B), ind(Indirect::HL)),
        0x47 => ld(r(B), r(A)),
        0x48 => ld(r(C), r(B)),
        0x49 => ld(r(C), r(C)),
        0x4A => ld(r(C), r(D)),
        0x4B => ld(r(C), r(E)),
        0x4C => ld(r(C), r(H)),
        0x4D => ld(r(C), r(L)),
        0x4E => ld(r(C), ind(Indirect::HL)),
        0x4F => ld(r(C), r(A)),
        0x50 => ld(r(D), r(B)),
        0x51 => ld(r(D), r(C)),
        0x52 => ld(r(D), r(D)),
        0x53 => ld(r(D), r(E)),
        0x54 => ld(r(D), r(H)),
        0x55 => ld(r(D), r(L)),
        0x56 => ld(r(D), ind(Indirect::HL)),
        0x57 => ld(r(D), r(A)),
        0x58 => ld(r(E), r(B)),
        0x59 => ld(r(E), r(C)),
        0x5A => ld(r(E), r(D)),
        0x5B => ld(r(E), r(E)),
        0x5C => ld(r(E), r(H)),
        0x5D => ld(r(E), r(L)),
        0x5E => ld(r(E), ind(Indirect::HL)),
        0x5F => ld(r(E), r(A)),
        0x60 => ld(r(H), r(B)),
        0x61 => ld(r(H), r(C)),
        0x62 => ld(r(H), r(D)),
        0x63 => ld(r(H), r(E)),
        0x64 => ld(r(H), r(H)),
        0x65 => ld(r(H), r(L)),
        0x66 => ld(r(H), ind(Indirect::HL)),
        0x67 => ld(r(H), r(A)),
        0x68 => ld(r(L), r(B)),
        0x69 => ld(r(L), r(C)),
        0x6A => ld(r(L), r(D)),
        0x6B => ld(r(L), r(E)),
        0x6C => ld(r(L), r(H)),
        0x6D => ld(r(L), r(L)),
        0x6E => ld(r(L), ind(Indirect::HL)),
        0x6F => ld(r(L), r(A)),
        0x70 => ld(ind(Indirect::HL), r(B)),
        0x71 => ld(ind(Indirect::HL), r(C)),
        0x72 => ld(ind(Indirect::HL), r(D)),
        0x73 => ld(ind(Indirect::HL), r(E)),
        0x74 => ld(ind(Indirect::HL), r(H)),
        0x75 => ld(ind(Indirect::HL), r(L)),
        0x76 => Instr::simple(exec_halt),
        0x77 => ld(ind(Indirect::HL), r(A)),
        0x78 => ld(r(A), r(B)),
        0x79 => ld(r(A), r(C)),
        0x7A => ld(r(A), r(D)),
        0x7B => ld(r(A), r(E)),
        0x7C => ld(r(A), r(H)),
        0x7D => ld(r(A), r(L)),
        0x7E => ld(r(A), ind(Indirect::HL)),
        0x7F => ld(r(A), r(A)),

        // 8bit ALU A,r
        0x80 => alu(exec_add, r(B)),
        0x81 => alu(exec_add, r(C)),
        0x82 => alu(exec_add, r(D)),
        0x83 => alu(exec_add, r(E)),
        0x84 => alu(exec_add, r(H)),
        0x85 => alu(exec_add, r(L)),
        0x86 => alu(exec_add, ind(Indirect::HL)),
        0x87 => alu(exec_add, r(A)),
        0x88 => alu(exec_adc, r(B)),
        0x89 => alu(exec_adc, r(C)),
        0x8A => alu(exec_adc, r(D)),
        0x8B => alu(exec_adc, r(E)),
        0x8C => alu(exec_adc, r(H)),
        0x8D => alu(exec_adc, r(L)),
        0x8E => alu(exec_adc, ind(Indirect::HL)),
        0x8F => alu(exec_adc, r(A)),
        0x90 => alu(exec_sub, r(B)),
        0x91 => alu(exec_sub, r(C)),
        0x92 => alu(exec_sub, r(D)),
        0x93 => alu(exec_sub, r(E)),
        0x94 => alu(exec_sub, r(H)),
        0x95 => alu(exec_sub, r(L)),
        0x96 => alu(exec_sub, ind(Indirect::HL)),
        0x97 => alu(exec_sub, r(A)),
        0x98 => alu(exec_sbc, r(B)),
        0x99 => alu(exec_sbc, r(C)),
        0x9A => alu(exec_sbc, r(D)),
        0x9B => alu(exec_sbc, r(E)),
        0x9C => alu(exec_sbc, r(H)),
        0x9D => alu(exec_sbc, r(L)),
        0x9E => alu(exec_sbc, ind(Indirect::HL)),
        0x9F => alu(exec_sbc, r(A)),
        0xA0 => alu(exec_and, r(B)),
        0xA1 => alu(exec_and, r(C)),
        0xA2 => alu(exec_and, r(D)),
        0xA3 => alu(exec_and, r(E)),
        0xA4 => alu(exec_and, r(H)),
        0xA5 => alu(exec_and, r(L)),
        0xA6 => alu(exec_and, ind(Indirect::HL)),
        0xA7 => alu(exec_and, r(A)),
        0xA8 => alu(exec_xor, r(B)),
        0xA9 => alu(exec_xor, r(C)),
        0xAA => alu(exec_xor, r(D)),
        0xAB => alu(exec_xor, r(E)),
        0xAC => alu(exec_xor, r(H)),
        0xAD => alu(exec_xor, r(L)),
        0xAE => alu(exec_xor, ind(Indirect::HL)),
        0xAF => alu(exec_xor, r(A)),
        0xB0 => alu(exec_or, r(B)),
        0xB1 => alu(exec_or, r(C)),
        0xB2 => alu(exec_or, r(D)),
        0xB3 => alu(exec_or, r(E)),
        0xB4 => alu(exec_or, r(H)),
        0xB5 => alu(exec_or, r(L)),
        0xB6 => alu(exec_or, ind(Indirect::HL)),
        0xB7 => alu(exec_or, r(A)),
        0xB8 => alu(exec_cp, r(B)),
        0xB9 => alu(exec_cp, r(C)),
        0xBA => alu(exec_cp, r(D)),
        0xBB => alu(exec_cp, r(E)),
        0xBC => alu(exec_cp, r(H)),
        0xBD => alu(exec_cp, r(L)),
        0xBE => alu(exec_cp, ind(Indirect::HL)),
        0xBF => alu(exec_cp, r(A)),

        0xC0 => Instr::with(N, cc(Cond::NZ), exec_ret_cc),
        0xC1 => Instr::with(rr(BC), N, exec_pop),
        0xC2 => Instr::with(N, cc(Cond::NZ), exec_jp),
        0xC3 => Instr::with(N, N, exec_jp),
        0xC4 => Instr::with(N, cc(Cond::NZ), exec_call),
        0xC5 => Instr::with(N, rr(BC), exec_push),
        0xC6 => alu(exec_add, IMM),
        0xC7 => Instr::with(Operand::Rst(0x00), N, exec_rst),
        0xC8 => Instr::with(N, cc(Cond::Z), exec_ret_cc),
        0xC9 => Instr::simple(exec_ret),
        0xCA => Instr::with(N, cc(Cond::Z), exec_jp),
        0xCB => Instr::simple(exec_cb_prefix),
        0xCC => Instr::with(N, cc(Cond::Z), exec_call),
        0xCD => Instr::with(N, N, exec_call),
        0xCE => alu(exec_adc, IMM),
        0xCF => Instr::with(Operand::Rst(0x08), N, exec_rst),
        0xD0 => Instr::with(N, cc(Cond::NC), exec_ret_cc),
        0xD1 => Instr::with(rr(DE), N, exec_pop),
        0xD2 => Instr::with(N, cc(Cond::NC), exec_jp),
        0xD4 => Instr::with(N, cc(Cond::NC), exec_call),
        0xD5 => Instr::with(N, rr(DE), exec_push),
        0xD6 => alu(exec_sub, IMM),
        0xD7 => Instr::with(Operand::Rst(0x10), N, exec_rst),
        0xD8 => Instr::with(N, cc(Cond::C), exec_ret_cc),
        0xD9 => Instr::simple(exec_reti),
        0xDA => Instr::with(N, cc(Cond::C), exec_jp),
        0xDC => Instr::with(N, cc(Cond::C), exec_call),
        0xDE => alu(exec_sbc, IMM),
        0xDF => Instr::with(Operand::Rst(0x18), N, exec_rst),
        0xE0 => Instr::simple(exec_ldh_n_a),
        0xE1 => Instr::with(rr(HL), N, exec_pop),
        0xE2 => ld(ind(Indirect::CFF), r(A)),
        0xE5 => Instr::with(N, rr(HL), exec_push),
        0xE6 => alu(exec_and, IMM),
        0xE7 => Instr::with(Operand::Rst(0x20), N, exec_rst),
        0xE8 => Instr::simple(exec_add_sp),
        0xE9 => Instr::simple(exec_jp_hl),
        0xEA => Instr::simple(exec_ld_abs_a),
        0xEE => alu(exec_xor, IMM),
        0xEF => Instr::with(Operand::Rst(0x28), N, exec_rst),
        0xF0 => Instr::simple(exec_ldh_a_n),
        0xF1 => Instr::with(rr(AF), N, exec_pop),
        0xF2 => ld(r(A), ind(Indirect::CFF)),
        0xF3 => Instr::simple(exec_di),
        0xF5 => Instr::with(N, rr(AF), exec_push),
        0xF6 => alu(exec_or, IMM),
        0xF7 => Instr::with(Operand::Rst(0x30), N, exec_rst),
        0xF8 => Instr::simple(exec_ldhl),
        0xF9 => Instr::simple(exec_ld_sp_hl),
        0xFA => Instr::simple(exec_ld_a_abs),
        0xFB => Instr::simple(exec_ei),
        0xFE => alu(exec_cp, IMM),
        0xFF => Instr::with(Operand::Rst(0x38), N, exec_rst),

        // 未定義オペコード: NOP として扱う
        _ => Instr::simple(exec_nop),
    }
}

/// CB プリフィックス命令のデコード
pub(super) fn decode_cb(cb: u8) -> Instr {
    use Reg8::*;
    let target = match cb & 0x07 {
        0 => r(B),
        1 => r(C),
        2 => r(D),
        3 => r(E),
        4 => r(H),
        5 => r(L),
        6 => ind(Indirect::HL),
        7 => r(A),
        _ => unreachable!(),
    };
    let n = (cb >> 3) & 0x07;
    match cb >> 6 {
        0 => {
            let e: ExecFn = match (cb >> 3) & 0x07 {
                0 => exec_cb_rlc,
                1 => exec_cb_rrc,
                2 => exec_cb_rl,
                3 => exec_cb_rr,
                4 => exec_cb_sla,
                5 => exec_cb_sra,
                6 => exec_cb_swap,
                7 => exec_cb_srl,
                _ => unreachable!(),
            };
            Instr::with(target, N, e)
        }
        1 => Instr::with(target, Operand::Bit(n), exec_cb_bit),
        2 => Instr::with(target, Operand::Bit(n), exec_cb_res),
        3 => Instr::with(target, Operand::Bit(n), exec_cb_set),
        _ => unreachable!(),
    }
}
